### ISSUE TITLE
Can't push Heroku (missing buildpack?) ImageOptim::BinResolver::Error: Bin resolving errors: remote: pngout worker: `pngout` not found; please provide proper binary or disable this worker

### ISSUE THREAD

**Issue by jasonfb** [toy/image_optim_rails#1]
The buildpacks on my environment are as follows

```
=== xyz-app Buildpack URLs
1. https://github.com/jasonfb/heroku-buildpack-cedar14-imagemagick704
2. https://github.com/bobbus/image-optim-buildpack
3. heroku/ruby
```

when I try to push to my environment with only image_optim, I am able to get through the build successfully. When add this gem
```
gem 'image_optim_rails'
```
and bundle install it, then push again to Heroku, I get:

https://gist.github.com/jasonfb/43a8e5aa4a7fe32205948110286a1c9e

**Comment by jasonfb** [comment]
UPDATE: 
When I have both gems installed:

```
gem 'image_optim_rails'
gem 'image_optim_pack'
```
it works & build cleanly :sunny:

**Comment by jasonfb** [comment]
RESOLVED; archived at SO http://stackoverflow.com/questions/42329978/imageoptimbinresolvererror-bin-resolving-errors-remote-pngout-worker-usi

**Comment by toy** [comment]
That was fast!
