### ISSUE TITLE
Missing  Documentation

### ISSUE THREAD

**Issue by certilremy** [toy/image_optim_rails#11]
Hi there, I Can't find good documentation at this time for this Gem, it seems useful but no documentation for rails. I want to use it to optimize the image that users upload to my web app.

**Comment by toy** [comment]
This gem is for optimising rails assets, optimising uploaded images depends on the way or gem you use for processing files and their transformation. Parent gem parent gem [image_optim](https://github.com/toy/image_optim#from-ruby) can be integrated into your pipeline to optimise image files or image data.

**Comment by certilremy** [comment]
> This gem is for optimizing rails assets, optimizing uploaded images depends on the way or gem you use for processing files and their transformation. Parent gem [image_optim](https://github.com/toy/image_optim#from-ruby) can be integrated into your pipeline to optimize image files or image data.

Good, thank you for the quick reply, I'm using the image_optim now, I thought this Gem does the same work and it's for rails. Now I understand.
