### ISSUE TITLE
Reduce rails Deps

### ISSUE THREAD

**Issue by BenMorganIO** [toy/image_optim_rails#13]
Thanks for the gem. I'm wondering if it's possible to reduce the amount of rails dependencies pulled in for this gem to what is base required?

For reference:

https://github.com/toy/image_optim_rails/blob/master/image_optim_rails.gemspec#L24

**Comment by toy** [comment]
Good idea, rails with all dependencies is definitely not needed

**Comment by toy** [comment]
This should do the trick: https://github.com/toy/image_optim_rails/compare/less-dependencies

**Comment by BenMorganIO** [comment]
Thank you!
